# Dockerfile for GEE 

FROM python:3.8-slim

# Set working directory
WORKDIR /app

# Install GEE dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements file
COPY requirements.gee.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.gee.txt
